version: '3'

services:
  server:
    build: ./server
    environment:
      - sctoken=${sctoken}
      - DATABASE_URL=mysql://root:${sctoken}@mysql:3306/socialcredit
    restart: unless-stopped
    ports:
      - ${apiport}:3000
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${sctoken}
      - MYSQL_DATABASE=socialcredit
    volumes:
      - socialcreditdata:/var/lib/mysql
    ports:
      - ${pubport}:3306
    restart: unless-stopped

volumes:
  socialcreditdata: